//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OracleLibrary.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PART
    {
        public decimal ID { get; set; }
        public string PARTNUMBER { get; set; }
        public string PARTNAME { get; set; }
        public string PARTDESCRIPTION { get; set; }
        public Nullable<decimal> QUANTITY { get; set; }
    }
}
